### ISSUE TITLE
research edge test cases

### ISSUE THREAD

**Issue by yoyota** [yoyota-archived/cs168-fall15-proj2-reliable-transport#2]
docs say
> Note that passing the example test cases is a
necessary but not sufficient condition for a good score on this project! These are only
meant as tests of basic functionality and examples for your own test cases; you must think
about the types of edge cases your sender could encounter, as well as the various conditions
required for correctness.

**Comment by huhuta** [comment]
hub cli test

**Comment by yoyota** [comment]
[juanpinzon's other test cases](https://github.com/juanpinzon/CS168-Proj2-ReliableTransport/tree/master/bears-tp/tests)
